# Exporting includes and lib name
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/pub)

SET(MP3_LIB_TYPE fixpt-helix)

SET(LIBRARIES ${LIBRARIES}
    ${MP3_LIB_TYPE}
)

ADD_LIBRARY(${MP3_LIB_TYPE} STATIC IMPORTED)
SET_PROPERTY(TARGET ${MP3_LIB_TYPE} PROPERTY IMPORTED_LOCATION ${CMAKE_BINARY_DIR}/${MP3_LIB_TYPE}/lib${MP3_LIB_TYPE}.a)